### ISSUE TITLE
Support for config parameter 

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/gulp-galenframework#2]
see https://github.com/galenframework/galen/issues/367

**Comment by hypery2k** [comment]
@renet could you please try the latest develop branch? Currently not having much time and wanted to release version 2.3 soon

**Comment by renet** [comment]
I'm sorry, I'm going on vacation on Saturday and thus I don't have the time right now. I may take a look at it, when I'm back - but I can't promise...
