### ISSUE TITLE
Possibility to change driver and binary

### ISSUE THREAD

**Issue by Regaddi** [hypery2k/gulp-galenframework#29]
Hey,

is it possible to change the driver and binary?
I'd like to use PhantomJS for my tests but failed to activate it.

When reading the [galen docs](http://galenframework.com/docs/reference-working-in-command-line/#Providingsystemproperties) I found the system properties section, which totally suits my needs: `-Dphantomjs.binary.path=/opt/phantomjs/bin/phantomjs`

How can I pass this option to gulp-galenframework?

All the best,

Chris

**Comment by Regaddi** [comment]
I've found out, that you provide the `properties` option.
But it seems, that this can only contain properties, that are usually defined in a `galen.config` file.
I suggest to make the path to a `galen.config` file configurable.
Additionally it would be great if there was an option, that contains galen CLI parameters, like `-Dphantomjs.binary.path=/opt/phantomjs/bin/phantomjs`.
This would make this tool super flexible 😃

**Comment by hypery2k** [comment]
currently it's not possible. I will try to add it in feature versions

**Comment by Regaddi** [comment]
Do you need any help with that?

**Comment by hypery2k** [comment]
any PR is welcome

**Comment by hypery2k** [comment]
have your tried using the properties object for this, see [here](https://github.com/hypery2k/gulp-galenframework#global-options).

**Comment by Regaddi** [comment]
Haven't worked on it for a while, since this is only an experimental / explorational task at work :)

**Comment by hypery2k** [comment]
closed due to no feedback
